networks:
  dofTrader_network:
    external: false

volumes:
  postgres_data:
    driver: local

services:
  express-js:
    build:
      context: ./expressJs
    container_name: express_app
    working_dir: /app
    volumes:
      - ./expressJs:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - dofTrader_network

  front:
    build:
      context: ./vueJs
    container_name: vue_front
    working_dir: /app
    volumes:
      - ./vueJs:/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - dofTrader_network
    tty: true


  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doftrader
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dofTrader_network